name: FirstPlugin
author: NCH
version: 1.0
main: me.nch.firstplugin.FirstPlugin

commands:
    firstcommand:
        description: The first command of the plugin.
        
permissions: 
    firstplugin.command:
        description: Run the command of the plugin.
        default: op        